
name: Generate CycloneDX SBOM

on:
  push:
    branches:
      - main

jobs:
  build-and-sbom:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
         
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23' 

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install cyclonedx-gomod
      run: |
        go install github.com/CycloneDX/cyclonedx-gomod/cmd/cyclonedx-gomod@latest

    - name: Install CycloneDX CLI
      run: |
              CYCLONEDXCLI_LATEST_URL=`curl -s https://api.github.com/repos/CycloneDX/cyclonedx-cli/releases/latest | jq -r '.assets[] | select(.name | contains ("-linux-x64")) | .browser_download_url' | grep -v md5`
              mkdir -p /opt/cyclonedx-cli
              wget -q -O /opt/cyclonedx-cli/cyclonedx-cli ${CYCLONEDXCLI_LATEST_URL}
              chmod +x /opt/cyclonedx-cli/cyclonedx-cli
              ln -s /opt/cyclonedx-cli/cyclonedx-cli /usr/local/bin/cyclonedx-cli
              cyclonedx-cli -h
        
    - name: Generate CycloneDX SBOM
      run: |
        cyclonedx-gomod mod -output sbom_uns.json

    - name: Sign SBOM File with CycloneDX CLI 
      run: |
        cyclonedx keygen --private-key-file private.key --public-key-file public.key
        cyclonedx sign bom sbom_uns.json --key-file private.key
        
    - name: Upload SBOM artifact
      uses: actions/upload-artifact@v4
      with:
        name: sbom
        path: sbom_uns.json
