
name: Generate CycloneDX SBOM

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-sbom:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
         
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23' 

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install cyclonedx-gomod
      run: |
        go install github.com/CycloneDX/cyclonedx-gomod/cmd/cyclonedx-gomod@latest
       
    - name: Generate CycloneDX SBOM
      run: |
        cyclonedx-gomod mod -output sbom1.json

    - name: Install Cosign
      uses: sigstore/cosign-installer@v3
         
    - name: Cosign (Keyless)
      run: |
         cosign sign-blob --yes \
          --output-signature sbom1.json.sig \
          --output-certificate sbom1.json.crt \
          sbom.json

             
    - name: Upload SBOM artifact
      uses: actions/upload-artifact@v4
      with:
        name: sbom1
        path: sbom1.json

    - name: Upload Signature
      uses: actions/upload-artifact@v4
      with:
        name: Raw signature1
        path: sbom1.json.sig

    - name: Upload Certificate1
      uses: actions/upload-artifact@v4
      with:
        name: Certificare
        path: sbom1.json.crt
